
MAKE	?= make
DIRS	= adapter dispatch language
LN	?= ln

all:
	for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple ARCH=`uname -p`; \
	done
	${CXX} -shared -o libngs-sdk.so.1.3.0 -Wl,-soname=libngs-sdk.so.1 \
		*/*.o -L./dispatch -lngs-disp
	${LN} -sf libngs-sdk.so.1.3.0 libngs-sdk.so.1
	${LN} -sf libngs-sdk.so.1.3.0 libngs-sdk.so

clean:
	for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple clean; \
	done
