
MAKE	?= make
DIRS	= ngs-sdk

MKDIR	?= mkdir
INSTALL	?= install
PREFIX	?= /usr/local
DESTDIR	?= ./stage

all:
	@for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple; \
	done

clean:
	@for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple clean; \
	done

install:
	${MKDIR} -p ${DESTDIR}${PREFIX}/lib
	${INSTALL} -c */*.a */*/*.a ${DESTDIR}${PREFIX}/lib
