
MAKE	?= make
DIRS	= ngs-sdk

MKDIR	?= mkdir
INSTALL	?= install
RM	?= rm

PREFIX	?= /usr/local
DESTDIR	?= ./stage

all:
	@for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple; \
	done

clean:
	@for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple clean; \
	done
	${RM} -rf ${DESTDIR}

install: all
	${MKDIR} -p ${DESTDIR}${PREFIX}/lib
	${INSTALL} -c ngs-sdk/*/*.a ngs-sdk/language/*/*.a ${DESTDIR}${PREFIX}/lib
