
MAKE    ?= make
DIRS    = ngs-sdk ngs-java

MKDIR   ?= mkdir
INSTALL ?= install
RM      ?= rm

PREFIX  ?= /usr/local
DESTDIR ?= ./stage

all:
	@for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple; \
	done

clean:
	@for dir in ${DIRS}; do \
	    ${MAKE} -C $$dir -f Makefile.simple clean; \
	done
	${RM} -rf ${DESTDIR}

install: all
	${MKDIR} -p ${DESTDIR}${PREFIX}/lib
	${INSTALL} -c ngs-sdk/*/*.a ngs-sdk/language/*/*.a \
		${DESTDIR}${PREFIX}/lib
	${INSTALL} -c ngs-sdk/*.so* ${DESTDIR}${PREFIX}/lib
	${MKDIR} -p ${DESTDIR}${PREFIX}/include/ngs/adapter \
		${DESTDIR}${PREFIX}/include/ngs/inl \
		${DESTDIR}${PREFIX}/include/ngs/itf \
		${DESTDIR}${PREFIX}/include/ngs/unix/`uname -p`
	${INSTALL} -c ngs-sdk/ngs/*.hpp ${DESTDIR}${PREFIX}/include/ngs
	${INSTALL} -c ngs-sdk/ngs/adapter/*.hpp ngs-sdk/ngs/adapter/*.h \
		${DESTDIR}${PREFIX}/include/ngs/adapter
	${INSTALL} -c ngs-sdk/ngs/inl/*.hpp ${DESTDIR}${PREFIX}/include/ngs/inl
	${INSTALL} -c ngs-sdk/ngs/itf/*.hpp ngs-sdk/ngs/itf/*.h \
		${DESTDIR}${PREFIX}/include/ngs/itf
	${INSTALL} -c ngs-sdk/ngs/unix/`uname -p`/*.h \
		${DESTDIR}${PREFIX}/include/ngs/unix/`uname -p`
	${MKDIR} -p ${DESTDIR}${PREFIX}/share/java/classes
	${INSTALL} -c ngs-java/ngs-java.jar \
		${DESTDIR}${PREFIX}/share/java/classes
