
BIN     = ngs-java.jar

RM	?= rm

all:	${BIN}

${BIN}:	ngs/*.java
	javac \
		ngs/ErrorMsg.java \
		ngs/Statistics.java \
		ngs/Fragment.java \
		ngs/FragmentIterator.java \
		ngs/Read.java \
		ngs/ReadIterator.java \
		ngs/ReadGroup.java \
		ngs/ReadGroupIterator.java \
		ngs/Alignment.java \
		ngs/AlignmentIterator.java \
		ngs/PileupEvent.java \
		ngs/PileupEventIterator.java \
		ngs/Pileup.java \
		ngs/PileupIterator.java \
		ngs/Reference.java \
		ngs/ReferenceIterator.java \
		ngs/ReadCollection.java \
		ngs/Package.java \
		-d . -classpath . -sourcepath .:itf: && touch ngs-java-api

clean:
	${RM} -f ngs/*.class ngs-java-api
