/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_PileupEventItf */

#ifndef _Included_ngs_itf_PileupEventItf
#define _Included_ngs_itf_PileupEventItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetReferenceSpec
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_PileupEventItf_GetReferenceSpec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetReferencePosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_PileupEventItf_GetReferencePosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetMappingQuality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_PileupEventItf_GetMappingQuality
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetAlignmentId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_PileupEventItf_GetAlignmentId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetAlignment
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_PileupEventItf_GetAlignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetAlignmentPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_PileupEventItf_GetAlignmentPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetFirstAlignmentPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_PileupEventItf_GetFirstAlignmentPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetLastAlignmentPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_PileupEventItf_GetLastAlignmentPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetEventType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_PileupEventItf_GetEventType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetAlignmentBase
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_ngs_itf_PileupEventItf_GetAlignmentBase
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetAlignmentQuality
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_ngs_itf_PileupEventItf_GetAlignmentQuality
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetInsertionBases
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_PileupEventItf_GetInsertionBases
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetInsertionQualities
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_PileupEventItf_GetInsertionQualities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventItf
 * Method:    GetDeletionCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_PileupEventItf_GetDeletionCount
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
